class FieldName
  def initialize(name, options={})
    @name = name
    @aliases = []
    if alias_opt = options[:alias]
      case alias_opt
      when String, Symbol
        @aliases << alias_opt.to_s.dup
      when Array
        @aliases.concat(alias_opt.map {|a| a.to_s.dup})
      end
    end
    @display_name = options[:display_name]
    @validator = options[:validator]
  end

  attr_reader :name, :aliases, :display_name, :validator
end

module Lyra::Metadata::Fields
  ALBUM = 'ALBUM'
  ALBUMARTIST = 'ALBUMARTIST'
  ALBUMARTISTSORT = 'ALBUMARTISTSORT'
  AMAZON_ASIN = 'AMAZON_ASIN'
  ARTIST = 'ARTIST'
  ARTISTSORT = 'ARTISTSORT'
  ASIN = 'ASIN'
  BAND = 'BAND'
  BPM = 'BPM'
  CDDB_CATEGORY = 'CDDB_CATEGORY'
  COMMENT = 'COMMENT'
  COMPILATION = 'COMPILATION'
  COMPOSER = 'COMPOSER'
  COMPOSERSORT = 'COMPOSERSORT'
  COMPRESSION_RATIO = 'COMPRESSION-RATIO'
  CONDUCTOR = 'CONDUCTOR'
  COPYRIGHT = 'COPYRIGHT'
  DATE = 'DATE'
  DESCRIPTION = 'DESCRIPTION'
  DISC = 'DISC'
  DISCC = 'DISCC'
  DISCID = 'DISCID'
  DISCNAME = 'DISCNAME'
  DISCNUMBER = 'DISCNUMBER'
  DISCSUBTITLE = 'DISCSUBTITLE'
  DISCTOTAL = 'DISCTOTAL'
  DURATION = 'DURATION'
  ENCODEDBY = 'ENCODEDBY'
  ENCODER = 'ENCODER'
  ENCODING = 'ENCODING'
  ENCODINGDATE = 'ENCODING-DATE'
  ENSEMBLE = 'ENSEMBLE'
  FEATURING = 'FEATURING'
  GENRE = 'GENRE'
  KEY = 'KEY'
  METADATA_BLOCK_PICTURE = 'METADATA_BLOCK_PICTURE'
  MIXEDBY = 'MIXEDBY'
  MUSICBRAINZ_ALBUMARTISTID = 'MUSICBRAINZ_ALBUMARTISTID'
  MUSICBRAINZ_ALBUMID = 'MUSICBRAINZ_ALBUMID'
  MUSICBRAINZ_ALBUMSTATUS = 'MUSICBRAINZ_ALBUMSTATUS'
  MUSICBRAINZ_ALBUMTYPE = 'MUSICBRAINZ_ALBUMTYPE'
  MUSICBRAINZ_ARTISTID = 'MUSICBRAINZ_ARTISTID'
  MUSICBRAINZ_TRACKID = 'MUSICBRAINZ_TRACKID'
  OPUS = 'OPUS'
  PART = 'PART'
  PERFORMER = 'PERFORMER'
  RELEASECOUNTRY = 'RELEASECOUNTRY'
  REPLAYGAIN_ALBUM_GAIN = 'REPLAYGAIN_ALBUM_GAIN'
  REPLAYGAIN_ALBUM_PEAK = 'REPLAYGAIN_ALBUM_PEAK'
  REPLAYGAIN_REFERENCE_LOUDNESS = 'REPLAYGAIN_REFERENCE_LOUDNESS'
  REPLAYGAIN_TRACK_GAIN = 'REPLAYGAIN_TRACK_GAIN'
  REPLAYGAIN_TRACK_PEAK = 'REPLAYGAIN_TRACK_PEAK'
  TITLE = 'TITLE'
  TOTALTRACKS = 'TOTALTRACKS'
  TRACKNUMBER = 'TRACKNUMBER'
  VERSION = 'VERSION'
  WORK = 'WORK'
  YEAR = 'YEAR'
end
